---
name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    tags:
      - '**'
  pull_request:
    paths-ignore:
      - '.github/workflows/*.yml'

jobs:
  nano_build:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: compiled_app_binaries
      run_for_devices: '["nanos", "nanox", "nanosp"]'

  nano_test:
    name: Run ragger tests using the reusable workflow
    needs: nano_build
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      download_app_binaries_artifact: compiled_app_binaries
      test_dir: tests/functional
      run_for_devices: '["nanos", "nanox", "nanosp"]'
