---
name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    tags:
      - '**'
  pull_request:
    paths-ignore:
      - '.github/workflows/*.yml'

jobs:
  ledger_app_build:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: compiled_app_binaries
      run_for_devices: '["nanos", "nanox", "nanosp", "stax"]'

  ledger_app_test_function:
    name: Run ragger tests using the reusable workflow
    needs: ledger_app_build
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      download_app_binaries_artifact: compiled_app_binaries
      test_dir: tests/functional
      run_for_devices: '["nanos"]'

  ledger_app_test_unit:
    name: Unit tests
    needs: ledger_app_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build unit tests
        run: |
          cd tests/unit/
          make
      - name: Generate code coverage
        run: |
          cd tests/unit/
          make coverage
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: tests/unit/coverage
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tests/unit/coverage.info
          flags: unittests
          name: codecov-app-seed-tool
          fail_ci_if_error: true
          verbose: true
